### ISSUE TITLE
Allow passing an entire folder of files

### ISSUE THREAD

**Issue by capitanfindusfi** [CapitanFindusFI/carbonsh-cli#10]
By adding a new parameter, could be _"dir"_ **(-d)**, allow to scan the entire folder for files and run the process for each one of them separately

**Comment by karimelazzouni** [comment]
Will try working on that 🙂

**Comment by capitanfindusfi** [comment]
@karimelazzouni thank you! I'll check that right tomorrow

**Comment by capitanfindusfi** [comment]
Thank you! Just had to update package.json with 'queue-fifo'
