### ISSUE TITLE
Better-looking terminal application

### ISSUE THREAD

**Issue by capitanfindusfi** [CapitanFindusFI/carbonsh-cli#13]
By using something like [ora](https://github.com/sindresorhus/ora), make the terminal a bit more good-looking

**Comment by Trafitto** [comment]
Can i do this?

**Comment by capitanfindusfi** [comment]
@Trafitto go for it

**Comment by Trafitto** [comment]
(◠‿・)—☆

**Comment by Trafitto** [comment]
#14 Here the pr
