### ISSUE TITLE
Add all themes from carbon.now.sh

### ISSUE THREAD

**Issue by capitanfindusfi** [CapitanFindusFI/carbonsh-cli#2]
By visiting https://carbon.now.sh/, add all the themes to a "Themes" TypeScript type or Map, which should be available as `choices` inside the `yargs` parser. Also, use **_"seti"_** as default

**Comment by fuzzmz** [comment]
@CapitanFindusFI, was looking into this and was wondering if you want the `themes` choice to replace the existing `theme` option.

**Comment by Trafitto** [comment]
I can do this!!

**Comment by capitanfindusfi** [comment]
> @CapitanFindusFI, was looking into this and was wondering if you want the `themes` choice to replace the existing `theme` option.

Sorry @fuzzmz , I was planning to assign that to @Trafitto as he wanted to explore TypeScript from its basics

**Comment by Trafitto** [comment]
#6  here the pr

**Comment by capitanfindusfi** [comment]
Merged with [PR](https://github.com/CapitanFindusFI/carbonsh-cli/pull/6/)
