### ISSUE TITLE
Add parameter to change output

### ISSUE THREAD

**Issue by capitanfindusfi** [CapitanFindusFI/carbonsh-cli#4]
Update `yargs` parsing with an `-output` (alias) option, ideally `-o` shortened, which specify the output path for the screenshot file. Also, TypeScript types should be updated as expected

**Comment by capitanfindusfi** [comment]
@Trafitto wanna jump in?

**Comment by Trafitto** [comment]
It would be a pleasure! Let's go :mechanical_arm:

**Comment by Trafitto** [comment]
#11  Here the PR, Let me know if there is anything to change :grin:

**Comment by capitanfindusfi** [comment]
Closed with https://github.com/CapitanFindusFI/carbonsh-cli/pull/11
